export default function Head() {
  return (
    <>
      <title>Abyss</title>
      <meta content="width=device-width, initial-scale=1" name="viewport" />
      <meta name="description" content="Generated by create next app" />
      <link rel="icon" href="/favicon.ico" />
      <script async defer src="https://buttons.github.io/buttons.js" />
    </>
  );
}
